#!/usr/bin/env python

from ostools import *
import argparse
import json
import sys

openstack = OSTools('ostools.cfg')


def get_args():
    """Get command-line options"""
    parser = argparse.ArgumentParser(prog = "project_info",
                description = "Lookup project specific information",
                epilog = "")
    parser.add_argument("-p", "--project_id",
                        help="The project/tenant ID.")
    parser.add_argument("-n", "--name",
                        help="The project name")
    parser.add_argument("-u", "--users",
                        help="List project members.",
                        action="store_true")
    parser.add_argument("-f", "--floatingips",
                        help="List allocated floating IP's",
                        action="store_true")

    args = parser.parse_args()

    if not args.project_id and not args.name:
        print("You must select a search parameter!")
        parser.print_help()
        sys.exit(1)

    return args


def main():
    args = get_args()

    print("I don't do anything yet!")



if __name__ == '__main__':
    main()
